### ISSUE TITLE
face_web容器安装问题

### ISSUE THREAD

**Issue by Yoxode** [chenlinzhong/face-login#3]
请问一下为什么安装face_web一直处于这个状态
![image](https://user-images.githubusercontent.com/15013513/54973175-c14ac880-4f5c-11e9-8852-2200b9bc0fe9.png)
您给的安装face_web步骤应该是这一步结束了进入docker容器里面输入的命令吧
![image](https://user-images.githubusercontent.com/15013513/54973214-f525ee00-4f5c-11e9-9be9-9c34b8eddfc1.png)
因为第一次用docker，有些不太懂的地方。

**Comment by betsyalan** [comment]
我也是停在这里了，没办法输入后面的命令。

**Comment by HellenaWeng** [comment]
> 请问一下为什么安装face_web一直处于这个状态
> ![image](https://user-images.githubusercontent.com/15013513/54973175-c14ac880-4f5c-11e9-8852-2200b9bc0fe9.png)
> 您给的安装face_web步骤应该是这一步结束了进入docker容器里面输入的命令吧
> ![image](https://user-images.githubusercontent.com/15013513/54973214-f525ee00-4f5c-11e9-9be9-9c34b8eddfc1.png)
> 因为第一次用docker，有些不太懂的地方。

请问解决了吗

**Comment by chenlinzhong** [comment]
php的镜像之前用的是别人的，有点问题，现在重新打包了一个镜像，问题解决了
